language: java
jdk:
  - openjdk8

install: true
script: 
  - mvn clean install
  - mvn test -B
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)


cache:
  directories:
  - $HOME/.m2
  
  
notifications:
  email:abhash.kumar@techmahindra.com
