language: java
jdk:
  - openjdk8

install: true
script: 
  - mvn clean install
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B


cache:
  directories:
  - $HOME/.m2
  
  
notifications:
  email:abhash.kumar@techmahindra.com